steps:
integrationArtifactDownload:
     cpiApiServiceKeyCredentialsId: CPIAPISERVICEKEYCREDENTIALSID
    integrationFlowId: buyer.ingest.template.consumer_copy26March
    integrationFlowVersion: 1.2.61
    downloadPath: ./iflows
