name: SAP Cloud Integration deploy IFlow Test
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
jobs:
  build:
     runs-on:
        - ubuntu-latest
     timeout-minutes: 60
     steps:
      - name: integrationArtifactDeploy
        uses: SAP/project-piper-action@main
        with:
          step-name: integrationArtifactDeploy
          LEVEL: ${{ inputs.logLevel }}
          flags: --apiServiceKey ${{ secrets.CPIAPISERVICEKEYCREDENTIALSID }} --integrationFlowId ${{ github.event.inputs.tags }}

      - name: integrationArtifactDownload
        uses: SAP/project-piper-action@main
        with:
          step-name: integrationArtifactDownload
          flags: --apiServiceKey ${{ secrets.CPIAPISERVICEKEYCREDENTIALSID }} --integrationFlowId ${{ github.event.inputs.tags }} --integrationFlowVersion 1.2.61 --downloadPath IntegrationFlows/Zip
