name: SAP Cloud Integration deploy IFlow Test
on: 
  workflow_dispatch:
    inputs:
      Iflows:
        description: 'Iflow name'
      Version:
        description: 'Version name'
jobs:
  build:
     runs-on:
        - ubuntu-latest
     timeout-minutes: 60
     steps:
      - name: integrationArtifactDeploy
        uses: SAP/project-piper-action@main
        with:
          step-name: integrationArtifactDeploy
          LEVEL: ${{ inputs.logLevel }}
          flags: --apiServiceKey ${{ secrets.CPIAPISERVICEKEYCREDENTIALSID }} --integrationFlowId ${{ github.event.inputs.Iflows }}

      - name: integrationArtifactDownload
        uses: SAP/project-piper-action@main
        with:
          step-name: integrationArtifactDownload
          flags: --apiServiceKey ${{ secrets.CPIAPISERVICEKEYCREDENTIALSID }} --integrationFlowId ${{ github.event.inputs.Iflows }} --integrationFlowVersion ${{ github.event.inputs.Version }} --downloadPath IntegrationFlows/Zip
