name: SAP Cloud Integration deploy IFlow Test
on:
 workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: integrationArtifactDeploy
        uses: SAP/project-piper-action@main
        with:
          step-name: integrationArtifactDeploy
          flags: --apiServiceKey ${{ secrets.CPIAPISERVICEKEYCREDENTIALSID }} --integrationFlowId buyer.ingest.template.consumer_copy26March

      - name: integrationArtifactDownload
        uses: SAP/project-piper-action@main
        with:
          step-name: integrationArtifactDownload
          flags: --apiServiceKey ${{ secrets.CPIAPISERVICEKEYCREDENTIALSID }} --integrationFlowId buyer.ingest.template.consumer_copy26March --integrationFlowVersion 1.2.61 --downloadPath integration/AnyErpEnterpriseCustomerIntegration
