name: SAP Cloud Integration deploy IFlow Test ZIP
on:
 workflow_dispatch
jobs:
  build:
    runs-on:
      - self-hosted
      - 2cpu-2g
    timeout-minutes: 60
    
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.2
        with:
          files: integration/AnyErpEnterpriseCustomerIntegration
          path: ${{ github.workspace }}/result.zip
